### ISSUE TITLE
Bug:命令运行不起来

### ISSUE THREAD

**Issue by a455455b** [josercc/Pod-Template#1]
描述:在任意位置运行如下命令:
git clone https://github.com/josercc/Pod-Template.git && cd Pod-Template && GBPods-Template-CommandLine && open ./
都会报这个错误:
-bash: GBPods-Template-CommandLine: command not found

**Comment by josercc** [comment]
@a455455b 
![](http://ipicimage-1251019290.coscd.myqcloud.com/2018-05-25-100857.jpg)
这是示例

**Comment by josercc** [comment]
确实如此，明天看一下




| |
邮箱：josercc@163.com
|

签名由 网易邮箱大师 定制

在2018年05月25日 18:02，Artillery 写道：

描述:在任意位置运行如下命令:
git clone https://github.com/josercc/Pod-Template.git && cd Pod-Template && GBPods-Template-CommandLine && open ./
都会报这个错误:
-bash: GBPods-Template-CommandLine: command not found

**Comment by josercc** [comment]
@a455455b 已经修复在https://github.com/josercc/Pod-Template/commit/1405f4de8ba1c28b2aa375fc0c3f4b66f9899bf8

运行新命令试一下
git clone git@github.com:josercc/Pod-Template.git && cd Pod-Template && $PWD/GBPods-Template-CommandLine && open ./
